package ec.edu.ups.pw;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-02-01T11:47:25.572-05:00
 * Generated source version: 3.5.0
 *
 */
@WebServiceClient(name = "LibroSOAPService",
                  wsdlLocation = "file:/C:/Users/ByronPC/AppData/Local/Temp/tempdir12585811079962662146.tmp/LibroSOAP_1.wsdl",
                  targetNamespace = "http://bean.EVAVasquez_ByronSRV.ups.edu.ec/")
public class LibroSOAPService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://bean.EVAVasquez_ByronSRV.ups.edu.ec/", "LibroSOAPService");
    public final static QName LibroSOAPPort = new QName("http://bean.EVAVasquez_ByronSRV.ups.edu.ec/", "LibroSOAPPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/ByronPC/AppData/Local/Temp/tempdir12585811079962662146.tmp/LibroSOAP_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LibroSOAPService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/ByronPC/AppData/Local/Temp/tempdir12585811079962662146.tmp/LibroSOAP_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LibroSOAPService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LibroSOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LibroSOAPService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public LibroSOAPService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public LibroSOAPService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public LibroSOAPService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns LibroSOAP
     */
    @WebEndpoint(name = "LibroSOAPPort")
    public LibroSOAP getLibroSOAPPort() {
        return super.getPort(LibroSOAPPort, LibroSOAP.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LibroSOAP
     */
    @WebEndpoint(name = "LibroSOAPPort")
    public LibroSOAP getLibroSOAPPort(WebServiceFeature... features) {
        return super.getPort(LibroSOAPPort, LibroSOAP.class, features);
    }

}
