package ec.edu.ups.pw;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-02-01T11:47:25.567-05:00
 * Generated source version: 3.5.0
 *
 */
@WebService(targetNamespace = "http://bean.EVAVasquez_ByronSRV.ups.edu.ec/", name = "LibroSOAP")
@XmlSeeAlso({ObjectFactory.class})
public interface LibroSOAP {

    @WebMethod
    @RequestWrapper(localName = "crearLibro", targetNamespace = "http://bean.EVAVasquez_ByronSRV.ups.edu.ec/", className = "ec.edu.ups.pw.CrearLibro")
    @ResponseWrapper(localName = "crearLibroResponse", targetNamespace = "http://bean.EVAVasquez_ByronSRV.ups.edu.ec/", className = "ec.edu.ups.pw.CrearLibroResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String crearLibro(

        @WebParam(name = "arg0", targetNamespace = "")
        ec.edu.ups.pw.Libro arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getLibros", targetNamespace = "http://bean.EVAVasquez_ByronSRV.ups.edu.ec/", className = "ec.edu.ups.pw.GetLibros")
    @ResponseWrapper(localName = "getLibrosResponse", targetNamespace = "http://bean.EVAVasquez_ByronSRV.ups.edu.ec/", className = "ec.edu.ups.pw.GetLibrosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ec.edu.ups.pw.Libro> getLibros()
;
}
